# Generated by Django 4.1.7 on 2024-02-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_user_email_user_in_correct_words_user_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translate_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='word',
            name='translate_uz',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
